import {test} from 'node:test';
import assert from 'node:assert/strict';
import {deliverAsset} from './delivery';
import type {AssetRow} from './db/schema';
test('PDF delivery is inline so authenticated browser previews can display it',async()=>{const f=fixture('uploads/dam/personal/pdf'); const response=await deliverAsset({...row('pdf'),mimeType:'application/pdf'},f.deps);assert.equal(response.headers.get('Content-Type'),'application/pdf');assert.match(response.headers.get('Content-Disposition')??'',/^inline/);});
test('active HTML uploads remain attachments instead of executing on the app origin',async()=>{const f=fixture('uploads/dam/personal/html'); const response=await deliverAsset({...row('html'),mimeType:'text/html'},f.deps);assert.equal(response.headers.get('Content-Type'),'application/octet-stream');assert.match(response.headers.get('Content-Disposition')??'',/^attachment/);});
const row=(storageKey:string|null,ownerUserId:string|null=null)=>({id:'synthetic',source:'upload',url:'https://legacy.invalid/f/old',storageKey,tenantId:ownerUserId?null:'synthetic-organization',ownerUserId,name:'Image',originalFilename:'image.png',mimeType:'image/png'} as AssetRow);
function fixture(key:string|null){let reads=0,legacy=0;return{deps:{enabled:()=>true,keyForUrl:async()=>key,read:async()=>{reads++;return 'https://signed.invalid/private'},legacyUrl:async()=>{legacy++;return 'https://legacy.invalid/signed'},fetch:async()=>new Response('owned fixture bytes')},reads:()=>reads,legacy:()=>legacy};}
test('authorized legacy null-key uploads stream verified immutable GCS bytes without customer backfill',async()=>{const f=fixture('imports/verified');const asset=row(null);const response=await deliverAsset(asset,f.deps);assert.equal(response.status,200);assert.equal(await response.text(),'owned fixture bytes');assert.equal(asset.storageKey,null);assert.equal(f.reads(),1);assert.equal(f.legacy(),0);assert.equal(response.headers.get('Cache-Control'),'private, no-store');assert.equal(response.headers.get('X-Content-Type-Options'),'nosniff');});
test('authorized personal current GCS upload preserves private streamed delivery',async()=>{const f=fixture('uploads/dam/personal/image');const response=await deliverAsset(row('uploads/dam/personal/image','synthetic-owner'),f.deps);assert.equal(response.status,200);assert.equal(f.reads(),1);assert.equal(f.legacy(),0);assert.equal(response.headers.get('Content-Type'),'image/png');assert.match(response.headers.get('Content-Disposition')??'',/^inline/);});
test('legacy null-key upload with no verified mapping fails closed before signed URL or fetch',async()=>{const f=fixture(null);const response=await deliverAsset(row(null),f.deps);assert.equal(response.status,409);assert.equal(f.reads(),0);assert.equal(f.legacy(),0);});
test('video delivery forwards byte ranges and preserves partial content for Safari playback',async()=>{
 let seen:RequestInit|undefined;const f=fixture('uploads/dam/video');
 const response=await deliverAsset({...row('video'),mimeType:'video/mp4'},{...f.deps,fetch:async(_url:string,init?:RequestInit)=>{seen=init;return new Response('part',{status:206,headers:{'content-range':'bytes 0-3/100','accept-ranges':'bytes','content-length':'4'}})}},new Request('https://folders.axxes.app/file',{headers:{Range:'bytes=0-3'}}));
 assert.equal(new Headers(seen?.headers).get('Range'),'bytes=0-3');assert.equal(response.status,206);assert.equal(response.headers.get('Content-Range'),'bytes 0-3/100');
});
test('PDF with missing MIME metadata uses filename for inline preview',async()=>{const f=fixture('uploads/dam/pdf');const response=await deliverAsset({...row('pdf'),originalFilename:'report.pdf',mimeType:null},f.deps);assert.equal(response.headers.get('Content-Type'),'application/pdf');});
