import {test} from 'node:test';
import assert from 'node:assert/strict';
import {deliverAsset} from './delivery';
import type {AssetRow} from './db/schema';
const row=(storageKey:string|null,ownerUserId:string|null=null)=>({id:'synthetic',source:'upload',url:'https://legacy.invalid/f/old',storageKey,tenantId:ownerUserId?null:'synthetic-organization',ownerUserId,name:'Image',originalFilename:'image.png',mimeType:'image/png'} as AssetRow);
function fixture(key:string|null){let reads=0,legacy=0;return{deps:{enabled:()=>true,keyForUrl:async()=>key,read:async()=>{reads++;return 'https://signed.invalid/private'},legacyUrl:async()=>{legacy++;return 'https://legacy.invalid/signed'},fetch:async()=>new Response('owned fixture bytes')},reads:()=>reads,legacy:()=>legacy};}
test('authorized legacy null-key uploads stream verified immutable GCS bytes without customer backfill',async()=>{const f=fixture('imports/verified');const asset=row(null);const response=await deliverAsset(asset,f.deps);assert.equal(response.status,200);assert.equal(await response.text(),'owned fixture bytes');assert.equal(asset.storageKey,null);assert.equal(f.reads(),1);assert.equal(f.legacy(),0);assert.equal(response.headers.get('Cache-Control'),'private, no-store');assert.equal(response.headers.get('X-Content-Type-Options'),'nosniff');});
test('authorized personal current GCS upload preserves private streamed delivery',async()=>{const f=fixture('uploads/dam/personal/image');const response=await deliverAsset(row('uploads/dam/personal/image','synthetic-owner'),f.deps);assert.equal(response.status,200);assert.equal(f.reads(),1);assert.equal(f.legacy(),0);assert.equal(response.headers.get('Content-Type'),'image/png');assert.match(response.headers.get('Content-Disposition')??'',/^inline/);});
test('legacy null-key upload with no verified mapping fails closed before signed URL or fetch',async()=>{const f=fixture(null);const response=await deliverAsset(row(null),f.deps);assert.equal(response.status,409);assert.equal(f.reads(),0);assert.equal(f.legacy(),0);});
