export const FOLDERS_OPERATIONS=['list','folders','libraries','authorize','createFolder','rename','move','trash','restore','renameFolder','trashFolder','restoreFolder','delivery','uploadStart','uploadFinish','linkOffice','linkedOffice'] as const
export type FoldersOperation=typeof FOLDERS_OPERATIONS[number]
export type FolderCapabilities={canRead:boolean;canWrite:boolean;canDelete:boolean}
export type FolderAsset={id:string;name:string;folder:string|null;mimeType:string|null;fileSize:number|null;category:string|null;updatedAt:string;trashedAt:string|null;expiresAt:string|null;officeDocumentId:string|null;officeKind:'doc'|'sheet'|'slides'|null;capabilities:FolderCapabilities}
export type FolderEntry={id:string;path:string;trashedAt:string|null;expiresAt:string|null;capabilities:FolderCapabilities}
export type FolderLibrary={id:string;name:string;folder?:string;capabilities:FolderCapabilities}
export type FoldersContext={userId:string;tenantId:string}
export type FoldersList={items:FolderAsset[];nextCursor:string|null}
export type FolderListQuery={folder?:string|null;q?:string;cursor?:string;limit?:number;trash?:boolean}
export type UploadIntent={uploadId:string;grant:string;endpoint:string;expiresAt:string}
export type OfficeLink={assetId:string;folder:string|null;title:string;active:boolean}
